import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Product from '@/components/product'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Hoichoi Fashion',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
         {/* Header  */}
         <Header/>
         {/* products */}
         <Product/>
        {children}
        
       
        
        </body>
    </html>
  )
}
